import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavContextProvider from "@/context/NavContext";
import NavToogle from "@/components/NavToogle";
import MainSection from "@/components/MainSection";
import Sidebar from "@/components/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavContextProvider>
          <div className='bg-white flex flex-row flex-nowrap justify-center items-center gap-4 w-[100vw] h-[100vh] overflow-y-hidden overflow-x-hidden'>
            <NavToogle />
            <Sidebar />
            <div className='bg-green-200 w-full h-[100vh] p-[20px] overflow-y-auto'>
              {children}
            </div>
          </div>
        </NavContextProvider>
      </body>
    </html>
  );
}
